= Wie Freunde uns in die Irre führen

*Belletristik*

Zur Belletristik werden im Buchhandel die verschiedenen Formen der
Unterhaltungsliteratur gezählt wie beispielsweise die literarischen
Genres Roman und Erzählung. Die Belletristik ging aus dem
Buchhandelssegment der Belles Lettres (frz. „schöne Literatur“)
hervor. +
https://de.wikipedia.org/wiki/Belletristik[Wikipedia 2014]

„Schön“ ist für uns das, was wir erfahren *wollen*. Die Richtung des
Wollens ist durch zufällige Ereignisse bestimmt worden. Die zufälligen
Ereignisse geschehen nach wie vor. Dass der Wille dennoch eine bestimmte
Richtung haben kann und nicht dauernd herumeiert, liegt an der
rückkopplungsartigen Art der Naturkräfte. Die Festigung von Richtungen
ist eine wesentliche Aufgabe unseres Gehirns. Vergangenes wird bewertet
und sortiert. Dabei wird solches Verhalten und Denken, das die
körpereigene Belohnung bewirkt hat, für die Zukunft verstärkt. Auch
größere Formen wie Stämme, Vereine und Staaten festigen einmal gewählte
Richtungen mit ähnlichen Mechanismen. Wie für das Gute und das Böse gibt
es für das Schöne und das Hässliche aber keinen absoluten Maßstab.

Wenn einer ein gutes Buch liest, ein Buch, das ihm gefällt, so arbeitet
er an der weiteren Festigung seiner zufällig entstandenen
Willensrichtung. Er verabschiedet sich eine Weile von der äußeren Welt,
die ihm nicht die Erscheinungen hervorruft, die er sich wünscht, und
erzeugt sich mit Hilfe des Buches Erscheinungen, die er sich wünscht. Je
leichter das Lesen fällt, desto mehr ist dies ein Zeichen dafür, dass er
gerade eifrig an einer Willensfestigung arbeitet.

*Freunde*

Wie „gute“ Bücher sind Freunde Festiger des bereits gerichteten Willens.
Sie stellen die grundsätzliche Ausrichtung der Person nicht in Frage,
sonst wären es nicht die Freunde dieser, sondern bestärken die Person in
der gewählten Richtung. Eine breite zufällige Richtungsverteilung der
Willen wird durch zwischenmenschliche Kräfte ausgedünnt auf weniger
Vielfalt. Es bilden sich Gruppen ähnlichen Denkens. Man findet zu
gemeinsamer Kultur, Religion, Sprache. Abweichungen von der zufällig
entstandenen Norm können mehr oder weniger geduldet werden.

Sogar die echte Freundschaft ist immer Mischung von Selbstsucht und
Mitleid: erstere liegt im Wohlgefallen an der Gegenwart des Freundes,
dessen Individualität der unserigen entspricht, und *sie macht fast
immer den größeren Teil aus*; Mitleid zeigt sich in der aufrichtigen
Teilnahme an seinem Wohl und Wehe und den uneigennützigen Opfern, die
man diesem bringt. +
xref:Quellen#Schopenhauer-D[Schopenhauer-D 1. Buch §67]

*Schöne neue Welt*

In seinem Bestseller „Filter Bubble“ hat [Eli] Pariser das Unbehagen am
mitdenkenden Internet analysiert: Das Netz zeigte uns, „was es denkt,
dass wir sehen wollen“. Zufallsfunde und überraschende Begegnungen
werden dadurch immer seltener. Am Ende, so Pariser, vereinzeln die
Konzerne uns alle in separate Filterblasen, wo wir nur noch mit den
Echos unserer eigenen Überzeugungen leben. +
xref:Quellen#Hexenmeister[Hexenmeister]

Das Netz soll doch ein Freund sein!

*Einsamkeit*

Bei Wegfall der freundschaftlichen Kontakte kann die Zufälligkeit und
Grundlosigkeit des eigenen Wollens und Tuns, das nun nicht mehr von
außen gefestigt wird, offenbar werden. Dieses ist für viele das
Schlimmste an der Einsamkeit: der Verlust des vermeintlich vorhandenen
Sinns, der daran abgelesen worden war, wie die anderen das eigene
Verhalten und Wollen bewertet hatten.
