= Mandukya-Karika
:toc:
:toc-title: Auszüge

== Zweiter Teil, genannt Vaitathyam, "die Unwahrheit"

{empty}1. Alles, was wir im Traum sehen, +
Ist unwahr, sagen Weise uns, +
Weil alles dies nur inwendig, +
Weil es in uns beschlossen liegt;

{empty}2. Auch weil die Zeit zu kurz wäre +
Zum Besuch ferner Gegenden, +
Und weil wir ja beim Aufwachen +
Nicht sind in jenen Gegenden.

{empty}3. "Da sind nicht Wagen, nicht Straßen," +
Lehrt die Schrift und das Denken uns, +
So ist des Träumens Unwahrheit +
Erwiesen und auch offenbart.

{empty}4. Weil Vielheit hier nur inwendig, +
Ist sie es auch im Wachen nur; +
Hier wie dort ist nur Vorstellung, +
In uns beschlossen, hier wie dort.

{empty}5. Des Träumens Zustand und Wachens +
Als derselbe den Weisen gilt, +
Denn gleich ist beiden die Vielheit, – +
Aus diesem wohlerwiesnen Grund.

{empty}6. Was nicht vorher und nicht nachher, +
Ist auch nicht in der Zwischenzeit; +
Obwohl es unwahr ist, wird es +
Für nicht unwahr doch angesehn.

{empty}7. Des Wachens Tun ist zweckmäßig, +
Aber nicht, wenn wir träumen, mehr; +
Drum, weil es anfängt und aufhört, +
Kann auch es nur auf Trug beruhn.

{empty}8. Auch was am Traume neu, stammt nur +
Aus dem Geist, und wenn Götter ihm +
Erscheinen, schaut er sie so nur, +
Wie er über sie ward belehrt.

{empty}9. Was er träumend im Geist bildet +
Innerlich, das ist unreal, +
Wiewohl sein Geist es griff draußen, +
Als gesehn unwahr beides ist.

{empty}10. Was er wachend im Geist bildet +
Innerlich, das ist unreal, +
Wiewohl sein Geist es griff draußen, +
Folgerecht unwahr beides ist.

{empty}11. Wenn nun beiderlei Vielheiten +
Unwahr im Traum und Wachen sind, +
Wer erkennt beide Vielheiten, +
Wer stellt sie im Bewußtsein vor?

{empty}12. Durch Selbsttäuschung der Gott Âtman +
Stellt sein Selbst durch sich selber vor, +
Erkennend beide Vielheiten, – +
Feststeht dieser Vedântasatz.

{empty}13. Umwandelnd stellt er als andres +
Vor, was nur im Bewußtsein ist, +
Als draußen und als notwendig +
Stellt in sich es der Âtman vor.

{empty}14. Geist ist des Innern Zeitmesser, +
Die Vielheit der des Äußeren, +
Ihr Unterschied liegt nur hierin, +
Als Vorstellung sind beide gleich.

{empty}15. Undeutlich ist die Welt drinnen +
Deutlich die Welt, die draußen liegt; +
Dem Sinnorgan nach verschieden, +
Sind als Vorstellung beide gleich.

{empty}16. Die Seele stellt man vor erstlich, +
Sodann der Dinge Sonderheit, +
Der äußeren und der drinnen, +
Wie man weiß, so erinnert man.

{empty}17. Wie ein Strick, nicht erkannt deutlich +
Im Dunkeln, falsch wird vorgestellt +
Als Schlange, als ein Strich Wassers, +
So wird falsch vorgestellt das Selbst (âtman).

{empty}18. Wie, wenn der Strick erkannt deutlich, +
Und die falsche Vorstellung weicht, +
Er nur Strick bleibt unzweiheitlich, +
So, wenn deutlich erkannt, das Selbst.

{empty}19. Wenn er als Prâna's, als alle +
Die vielen Dinge uns erscheint, +
So ist das alles nur Blendwerk (mâyâ), +
Mit dem der Gott sich selbst betrügt.

{empty}20. Prâna-Kennern ist er Prâna's (Vaisheshika's), +
Elemente dem, der sie kennt (Lokâyatika's), +
Guna-Wissern ist er Guna's (Sânkhya's), +
Tattva's ist er dem, der sie kennt (Shaiva's).

{empty}21. Viertelwissern ist er Viertel (Mândûkya-Up.), +
Sinnlichkeitswissern Sinnlichkeit (Vatsyâyana), +
Den Weltraumwissern Welträume (Paurânika's), +
Götter den Götterkundigen (Veda-Anhängern).

{empty}22. Den Vedawissern ist Veda's, +
Den Opferwissern Opfer er, +
Genießer denen, die diesen, +
Genußobjekt, die dies verstehn.

{empty}28. Subtil für solche, die dieses, +
Grob für solche, die dies verstehn, +
Gestaltet denen, die dieses, +
Ungestaltet, die dies verstehn.

{empty}24. Zeit ist er für die Zeitwisser, +
Für Raumkenner ist er der Raum, +
Künste ist er für Kunstkenner, +
Weltschichten dem, der diese kennt.

{empty}25. Für Manas-Kenner ist Manas, +
Für Buddhi-Kenner Buddhi er, +
Geist ist er für die Geistwisser, +
Recht und Unrecht dem, der sie kennt.

{empty}26. Fünfundzwanzigfach für diese (Sânkhya's), +
Jenen als sechsundzwanzigster (Pâtanjala's), +
Einunddreißigfach für andre (Pâshupata's), +
Unendlich gilt für viele er.

{empty}27. Welten ist er dem Weltkenner, +
Lebensstadien, dem der sie kennt, +
Drei-Genushaft den Sprachlehrern, +
Andern nied'res und höheres.

{empty}28. Für Schöpfungswisser Weltschöpfung, +
Für Vergangwisser Weltvergang, +
Weltbestand für Bestandwisser, – +
So ist alles er allerwärts.

{empty}29. Welches Sein man so andichtet +
Dem Âtman, dafür hält er sich, +
Das hegt er und, zu ihm werdend, +
Gibt er ihm sich als Dämon hin.

{empty}30. Er selbst ist alle Seinsformen, +
Von denen er verschieden scheint, – +
Wer dies weiß, wird sich vorstellen +
Ohne Sehen, wie es wirklich ist.

{empty}31. Wie Traum nnd Blendwerk man ansieht, +
Wie eine Wüstenspiegelung, +
So sieht an dieses Weltganze, +
Wer des Vedânta kundig ist.

{empty}32. Kein Vergang ist und kein Werden, +
Kein Gebundner, kein Wirkender, +
Kein Erlösungsbedürftiger, +
Kein Erlöster, der Wahrheit nach.

{empty}33. Als unreale Seinsformen +
Und als Einer wird er gedacht, +
Doch wer sie denkt, ist stets Einer, +
Drum die Einheit den Sieg behält.

{empty}34. Nicht auf den Âtman stützt Vielheit +
Und auch nie auf sich selber sich, +
Nicht neben ihm und nicht durch ihn +
Kann bestehn sie, das ist gewiß.

{empty}35. Furcht, Zorn und Neigung ablegend, +
Schaut zweiheitlos und wandellos +
Der Weltausbreitung Aufhören +
Der Muni, der den Veda kennt.

{empty}36. Wer so erkannt der Welt Wesen, +
Der halte an der Einheit treu; +
Der Zweiheitlosigkeit sicher, +
Geht er kalt an der Welt vorbei.

{empty}37. Von Preisen frei und Lobsingen, +
Ja, auch ohne den Manenkult, +
In allem, was da lebt, heimisch, +
Lebt er so "wie es eben kommt".

{empty}38. Das Wesen in sich selbst sehend, +
Das Wesen in der Außenwelt, +
Zu ihm werdend, in ihm ruhend, +
Halt er treu an dem Wesen fest.

== Dritter Teil, genannt Advaitam, "die Zweiheitlosigkeit"

{empty}1. Verehrung das Gebot fordert +
Des Brahman als Gewordenen, +
Eh' es ward, war es noch nicht da, +
Drum armselig Verehrer sind.

{empty}2. Was nicht armselig, hört jetzo, +
Ungeboren, gleich allerwärts, +
Und warum nichts entsteht irgend, +
Obwohl entstehend überall.

{empty}3. Der Âtman gleicht dem Weltraume, +
Der Jîva gleicht dem Raum im Topf, +
Die Töpfe sind die Leibstoffe, +
Was "entstehn" heißt, dies Gleichnis zeigt.

{empty}4. Wenn die Töpfe zugrund gehen, +
Was wird dann aus dem Raum im Topf? +
Er zergeht in dem Weltraume, – +
So der Jîva im Âtman anch.

{empty}6. Wie, wenn in einem Topfraume +
Staub sich vorfindet oder Rauch, +
Nicht alle Räume dies teilen, +
So die Jîva's nicht Lust and Leid.

{empty}6. Ja, Formen, Wirkungen, Namen +
Sind verschieden nach ihrem Ort, +
Doch der Raum, den sie einnehmen, +
Ist sich gleich, – so die Jîva's auch.

{empty}7. Wie der Topfraum vom Weltraume +
Kein Produkt ist und anch kein Glied, +
So ist der Jîva vom Âtman +
Kein Produkt, auch kein Glied von ihm.

{empty}8. So wie der Himmelsraum Kindern +
[Obwohl farblos,] als blau erscheint, +
So scheint behaftet mit Flecken +
Unerfahrnen der Âtman auch.

{empty}9. Was Sterben und Entstehn angeht, +
Fortgehn und Wiederherkommen +
Und alle Körper Durchsetzen, – +
Ist dem Raume vergleichbar er.

{empty}10. Doch traumgleich alle Leibstoffe +
Als Trug der Âtman breitet aus; +
Weder als gleich, noch als ungleich +
An Rang lassen sie denken sich.

{empty}11. Als Seele (jîva) in den fünf Hüllen, +
So lehrt das Taittirîyakam, +
Der höchste Âtman verstockt ist, +
Er, den dem Raum verglichen wir.

{empty}12. Im Honigteile wird paarweis +
Das höchste Brahman aufgezeigt, – +
Wie in der Erd' und im Leibe, – +
Er, den dem Raum verglichen wir.

{empty}13. Wenn die Schrift Jîva und Âtman +
Durch Gleichsetzung für eins erklärt, +
Verwerfend alles Vielheitsein, +
So ist das wahr in vollem Sinn.

{empty}14. Doch wenn auch vor der Weltschöpfung +
Sie beide auseinander hält, +
So gilt das bildlich, nicht wörtlich, +
Und nur von dem, was werden soll.

{empty}15. Und wenn sie überhaupt Schöpfung +
Im Bild von Ton, Erz, Funken lehrt, +
So dient dies nur als Lehrmittel, +
Denn "nicht ist Vielheit irgendwie".

{empty}16. Schüler gibt es in drei Stufen, +
Schwache, mittlere, treffliche; +
Um ihrer willen, aus Mitleid +
Verehrungsobjekt Brahman wird.

{empty}17. Auf ihrer Sätze Standpunkt stehn +
Zuversichtlich die Zweiheitler, +
Doch widersprechen sie selbst sich, +
Bei uns fehlt dieser Widerspruch.

{empty}18. In Wahrheit ist die Unzweiheit, +
Zweiheit nur in der Spaltungswelt; +
Sie lehren beiderseits Zweiheit, +
Bei uns fehlt solcher Widerspruch.

{empty}19. Als Blendwerk nur besteht Spaltung +
Jenes Einzigen, Ewigen, +
Denn wäre Spaltung in Wahrheit, +
Sterblich würde, was ewig ist.

{empty}20. Vom ungeword'nen Sein nehmen +
Jene Lehrer ein Werden an, – +
Was ungeboren, unsterblich, +
Wie könnte sterblich werden das!

{empty}21. Was unsterblich, kann nicht sterblich, +
Was sterblich, nicht unsterblich sein, +
Kein Ding kann anders sein jemals, +
Als es seiner Natur nach ist.

{empty}22. Wenn ein unsterbliches Dasein +
Überginge in Sterblichsein, +
Nur scheinbar wär' es unsterblich, +
Wo bliebe seine Ewigkeit?

{empty}23. Von Wahrheit oder Schein redend, +
Stets von der Schöpfung Gleiches lehrt +
Die Schrift, sicher und grundhabend, +
Ist's, wie sie sagt, und anders nicht.

{empty}24. "Nicht ist hier Vielheit" so heißt es, +
"Durch Blendwerk vielfach Indrâ geht", +
"Als ungeboren wird vielfach" +
Durch Blendwerk nur geboren er.

{empty}25. Durch Bestreitung der Sambhûti +
Wird ein Entstehen abgewehrt; +
"Wer könnte ihn hervorbringen?" +
Dies Wort zeigt ihn als ursachlos.

{empty}26. Das Wort: "er ist nicht so, nicht so", +
Absprechend alles Sagbare, +
Kann, wie die Unerkennbarkeit +
Zeigt, auf Ihn sich beziehen nur.

{empty}27. Das Seiende kann nicht werden, +
Es wäre denn durch Blendwerk nur; +
Wer es in Wahrheit läßt werden, +
Läßt werden, was schon war vorher.

{empty}28. Nicht in Wahrheit, noch als Blendwerk +
Kann je entstehn Nichtseiendes; +
Ein Sohn der Unfruchtbaren wird +
Nicht in Wirklichkeit, noch im Schein.

{empty}29. Wie im Traume der Geist regt sich, +
Als viel scheinend durch Täuschung nur, +
So im Wachen der Geist regt sich, +
Als viel scheinend durch Täuschung nur.

{empty}30. Als viel erscheint, der nur eins ist, +
Im Traum der Geist, – das ist ja klar; +
Als viel erscheint, der nur eins ist, +
Der wache Geist, – auch das ist klar.

{empty}40. Der Geist muß unterdrückt werden, +
Damit zuteil dem Yogin wird +
Das Furchtlose, das Schmerzlose, +
Die Erweckung, die ew'ge Ruh.

{empty}41. Wie wenn zerfließt im Weltmeere +
Der Tropfen, der am Grashalm hing, +
So des Geistes Unterdrückung +
Erfolgt ohne Beschwerlichkeit.

{empty}42. Man unterdrücke methodisch +
Den Geist, den Wunsch und Lust zerstreut, +
Ganz ruhig wird er dann schwinden, +
Sein Schwinden ist wie Liebeslust.

{empty}43. Man weiß, daß alles voll Schmerzen, +
Und wendet sich von Wunsch und Lust; +
Man weiß, daß alles nur Brahman, +
Und sieht nicht das Gewordne mehr.

{empty}44. Weckt den Geist, will er nichts werden (einschlafen), +
Sammelt ihn, will er sich zerstreun; +
Beides wisse man als sündhaft; +
Ward er brahmangleich, stört ihn nicht!

{empty}45. Freilich schmeckt er dann nicht Lust mehr, +
Keiner Begierde sich bewußt; +
Sein Denken, ungestört wirkend, +
Strebe eifrig zur Einheit hin.

{empty}46. Wenn dann weder im Schlaf schwindet +
Der Geist, noch auch Zerstreuung sucht, +
Dann tritt hervor er als Brahman, +
Regungslos und vom Scheine frei.

{empty}47. Als frei, beruhigt und leidlos, +
Als unaussprechlich höchste Lust, +
Als ewig, ewigen Objekts +
Allbewußt, schildern Kenner es.

{empty}48. Keine Seele entsteht jemals, +
Kein Entsteh'n ist der ganzen Welt, +
Das ist die höchste Heilswahrheit, +
Daß es nirgend ein Werden gibt!

== Vierter Teil, genannt Alâtashânti, "die Beilegung des Feuerbrandes"

{empty}1. Der wie Wolken im Weltraume +
Die Vielheiten im Einen weiß, +
Das Subjekt und zugleich Objekt +
Ist, – ihn ehr' ich, den Purusha!

{empty}2. Den wir als Ungefühl-Yoga, +
Allem Seienden freund und gut, +
Widerspruchlos, unanfechtbar, +
Aufgezeigt, – ihm Verehrung sei!

{empty}3. "Ein Werden ist nur des, was ist", +
So sagen manche Denker uns; – +
"Nein! des, was nicht ist", so andre, +
Gegenseitig in Widerspruch.

{empty}4. "Was ist, das kann doch nicht werden!" – +
"Was nicht ist, kann auch werden nicht!" – +
So streitend, für das Nichtwerden, +
Gleich Nichtzweiheitlern, zeugen sie.

{empty}5. Uns freut, wenn sie dadurch zeigen, +
Daß ein Werden unmöglich ist; – +
Daß wir uns nicht, wie sie alle,. +
Widersprechen, das höret jetzt.

{empty}6. Des Ungewordenen Werden +
Nehmen jene Behaupter an, +
Doch, was nicht ward, was unsterblich, +
Wie könnte sterblich werden das?

{empty}7. Was unsterblich, kann nicht sterblich, +
Was sterblich, nicht unsterblich sein, +
Sein Ding kann anders sein jemals, +
Als es seiner Natur nach ist.

{empty}8. Wenn ein unsterbliches Wesen +
Überginge in Sterblichsein, +
Nur scheinbar war' es unsterblich, +
Wo bliebe seine Ewigkeit?

{empty}9. Wesenseigen, bestandbildend, +
Angeboren und ungemacht, +
Das eigne Sein nie aufgebend, – +
So ist, was "die Natur" (prakrti) man nennt.

{empty}10. Ungeboren und unsterbend +
Sind Selbstheiten (dharma) dem Wesen nach; +
Der ist der Selbstheit unkundig, +
Der sie entstehn und sterben läßt.

{empty}11. Für wen die Ursach wird Wirkung, +
Der läßt werden die Ursache, – +
Wie kann, was ewig ist, werden? +
Wie, was eigen ist, trennen sich?

{empty}12. Wird die Ursache selbst Wirkung, +
Dann ist ewig die Wirkung schon, +
Und doch wird sie! und ihr Werden +
Läßt die Ursach verloren gehn!

{empty}13. Neinl Wer das Ew'ge läßt Werden, +
Dem steht keine Erfahrung bei; . +
Und wer Gewordnes läßt werden, +
Verfällt in ewigen Regreß!

{empty}14. Wenn ein Erfolg des Grunds Ursprung, +
Und der Grund Ursprung des Erfolgs, +
Dann wären anfanglos beide, +
Grund und Erfolg, wie kann das sein?

{empty}15. Wenn ein Erfolg des Grunds Ursprung, +
Und der Grund Ursprung des Erfolgs, +
Dann ist wohl das Entstehn beider, +
Wie wenn der Sohn den Vater zeugt?

{empty}16. Grund und Erfolg, wenn entstanden, +
Erheischen Reihenfolge doch; +
Denn entstehen sie gleichzeitig, +
Wie zwei Hörner, so fehlt das Band.

{empty}17. Daß aus Erfolgen entspränge +
Der Grund selbst, ist beweisbar nicht, +
Und ist der Grund unbeweisbar, +
Wie kann er wirken den Erfolg?.

{empty}18. Wenn aus Erfolg der Grund folgte +
Und aus dem Grunde der Erfolg, +
Welcher von beiden ist früher, +
Und sein Folgen nur relativ?

{empty}19. So legt Unmöglichkeit, Unsinn +
Und Verwirrung der Zeitordnung, +
In die die Gegner stets fallen, +
Für das Nichtwerden Zeugnis ab.

{empty}20. Der Fall von Samen und Pflanze +
Ist nur scheinbar beweisend hier; +
Was aber nur beweist scheinbar, +
Ist zum Beweisen tauglich nicht.

{empty}21. Der Widersinn der Zeitfolge +
Bestätigt das Nichtwerden nur; +
Da Werdendes zurückweisen +
Sicher würde auf Früheres.

{empty}22. Nicht aus sich selbst, noch aus anderm +
Kann ein Wesen entstehen je; +
Nicht als seiend, noch nichtseiend, +
Noch als beides, kann es entstehn.

{empty}23. Grund und Erfolg, wenn anfanglos, +
Schließen das Werden von sich aus; +
Wofür es gibt keinen Anfang, +
Dafür gibt keinen Anfang es.

{empty}24. Wahrnehmung müsse Grund haben, +
Weil unmöglich ihr Wechseln sonst, +
Auch sei von uns unabhängig +
Schmerz und Wahrnehmung, – meinen sie.

{empty}25. Wahrnehmung müsse Grund haben, +
So beweisen sie künstlich uns, – +
Doch daß der Grund keinen Grund hat, +
Das lehrt Wesensbetrachtung uns.

{empty}26. Der Geist berührt nicht Objekte +
Und auch nicht der Objekte Schein; +
Wenn unreal die Objekte, +
Ist's auch, vom Geist getrennt, ihr Schein.

{empty}27. Auch nicht, in den drei Zeitläuften, +
Berührt je ein Objekt den Geist; +
Grundloser Schein noch viel wen'ger; +
Wie könnte werden der zum Grund!

{empty}28. Darum ist nirgend ein Werden, +
Im Subjekt nicht, im Objekt nicht; +
Wer eins von beiden läßt werden, +
Der wandelt in den Wolken nur.

{empty}29. Weil sonst das Ewige würde, +
Ist unwerdend die Wesenheit; +
Kein Ding kann anders sein jemals, +
Als es seiner Natur nach ist.

{empty}30. War' anfanglos der Samsâra, +
So könnte er nicht endlich sein; +
Wär' die Erlösung anfangend, +
Sie könnte nicht unendlich sein.

{empty}31. Was nicht vorher und nicht nachher, +
Ist auch nicht in der Zwischenzeit; +
Obwohl es unwahr ist, wird es +
Für nicht unwahr doch angesehn.

{empty}32. Des Wachens Tun ist zweckmäßig, +
Aber nicht, wenn wir träumen, mehr; +
Drum, weil es anfängt und aufhört, +
Kann auch es nur auf Trug beruhn.

{empty}33. Was im Traume wir wahrnehmen, +
Ist irrig, weil im Körper nur; +
Wie ließen Dinge sich schauen +
In diesem eingeschlossnen Raum?

{empty}34. Auch ist die Zeit nicht hinreichend, +
Hinzugehen, um sie zu sehn; +
Auch finden wir beim Aufwachen +
Uns nicht da, wo wir sie gesehn.

{empty}35. Und was mit andern man absprach, +
Besteht nicht mehr, wenn man erwacht; +
Und was im Traume man faßte, +
Hält man, erwacht, in Händen nicht.

{empty}36. Auch was wir von dem Leib träumen, +
Ist unwahr und nicht wie es ist; – +
Unwahr wie dieses, ist alles, +
Was der Geist nimmt im Wachen wahr.

{empty}37. Was wir, wie wachend, wahrnehmen +
Im Traum, hat seinen Grund in uns; +
So hat in uns seinen Grund auch, +
Was wir im Wachen nehmen wahr.

{empty}38. Unbegreiflich ist Entstehung; +
Alles als ewig lehrt die Schrift; +
Nimmermehr kann hervorgehen +
Aus Seiendem Nichtseiendes (Werdendes).

{empty}39. Nichtseiendes sehn wir wachend; +
Das Traumbild ist aus gleichem Stoff: +
Nichtseiendes sehn wir träumend; +
Wenn wir erwachen, ist es nichts.

{empty}40. Nichtsein gebiert doch nicht Nichtsein, +
Nichtsein gebiert auch nicht das Sein; +
Und auch das Sein gebiert Sein nicht; +
Sein kann Nichtsein gebären nicht.

{empty}41. Wie man im Wachen aus Irrtum +
Unmögliches als seiend faßt, +
So auch im Traume aus Irrtum +
Sieht man Wesen erscheinen sich.

{empty}42. Aus Wahrnehmung und Herkommen +
Halten am Realismus sie; +
Was sie kennen ist nur Werden, +
Zurückschreckend von dem, was ist.

{empty}43. Manche, vom Sein zurückschreckend, +
Wenn auch nicht bloße Wahrnehmler, +
Des Werdens Mängel nicht meiden; +
Mängel bleiben es, wenn auch klein.

{empty}44. Durch Wahrnehmung, durch Herkommen +
Heißt auch ein Blendwerk Elefant; +
Durch Wahrnehmung, durch Herkommen +
Heißt auch das Ding ein seiendes.

{empty}45. Werden ist Schein, Bewegung Schein, +
Das Dingliche ist bloßer Schein; +
Nichtwerdend, unbewegt, dinglos, +
Still, zweiheitlos die Wahrheit ist.

{empty}46. So ist kein Werden im Subjekt, +
Im Objekte kein Werden ist; +
Wer dieses hat erkannt einmal, +
Fällt nicht zurück ins Gegenteil.

{empty}47. Wie Funkenschwingung den Schein gibt +
Grader und krummer Linien, +
So den Schein Bewußtseinsschwingung +
Von Auffassen und Auffasser.

{empty}48. Wie ungeschwungen der Funke +
Nicht erscheint, nicht entsteht (als Kreis), +
So Bewußtsein ungeschwungen +
Erscheint nicht und entsteht auch nicht.

{empty}49. Schwingt der Funke, so kommt der Schein +
Nicht von außen her irgendwie, +
Nicht von anderm als dem Schwingen, +
Nicht ist Zuwachs dem Funken er.

{empty}50. Auch nicht entflieht er dem Funken, +
Weil er nicht hat ein Wirklichsein, +
Ebenso ist's beim Erkennen, +
Denn auch dieses ist bloßer Schein.

{empty}51. Schwingt Erkenntnis, so kommt der Schein +
Nicht von außen her irgendwie, +
Nicht von anderm als dem Schwingen, +
Nicht ist Bewußtseinszuwachs er.

{empty}52. Nicht entflieht er dem Bewußtsein, +
Weil er nicht hat ein Wirklichsein; +
Weil Verursachtsein unwirklich, +
Ist als wirklich undenkbar er.

{empty}53. Ein Ding, so meint man, sei Ursach +
Des Daseins für ein andres Ding, +
Doch für die Wesenheit gibt es +
Kein Dingsein und kein Anderssein.

{empty}54. Weder aus Geist entspringt Dasein, +
Noch aus Dasein entspringt der Geist; +
Drum nehmen Weise kein Werden +
Des Grunds oder Erfolges an.

{empty}55. Wer noch Grund und Erfolg annimmt, +
Dem entstehn aus einander sie; +
Wer frei von dieser Annahme, +
Für den entstehen sie nicht mehr.

{empty}56. Wer noch Grund und Erfolg annimmt, +
Für den streckt der Samsâra sich; +
Wer frei von dieser Annahme, +
Der ist auch vom Samsâra frei.

{empty}57. Wer geistumnachtet, sieht werdend +
Alles, ein Ew'ges kennt er nicht; +
In Wahrheit alles ist ewig, +
Vernichtetwerden gibt es nicht.

{empty}58. Die Wesenheiten, die werden, +
Die werden nicht in Wirklichkeit; +
Ihr Entstehen ist nur Blendwerk, +
Und Blendwerk ist nicht Wirklichkeit.

{empty}59. Wie, wo der Same nur Blendwerk, +
Auch die Pflanze ein solches ist, +
Nicht wesenhaft noch austilgbar, +
So steht's mit allen Dingen hier.

{empty}60. Da alle Dinge nicht wirklich, +
Gibt nicht Dauer es noch Vergang; +
Wo alle Farben wegfallen, +
Ist keine Unterscheidbarkeit.

{empty}61. Wie in des Traumes Scheinvielheit +
Der Geist irrtümlich ist verstrickt, +
So in des Wachens Scheinvielheit +
Ist irrtümlich der Geist verstrickt.

{empty}62. Wie träumend eine Schein-Vielheit +
Erblickt der vielheitlose Geist, +
So wachend eine Schein-Vielheit +
Erblickt der vielheitlose Geist.

{empty}63. Was man, im Traum umherschweifend +
In allen Himmelsgegenden, +
An Tieren, Vögeln, Insekten +
Nur immer wahrzunehmen meint,

{empty}64. Das besteht nirgendwo anders +
Als im Geiste des Träumenden; +
Drum alles, was er dann sieht, ist +
Nur Bewußtsein des Träumenden.

{empty}65. Was man, wachend umherschweifend +
In allen Himmelsgegenden, +
An Tieren, Vögeln, Insekten +
Nur immer wahrzunehmen meint,

{empty}66. Das besteht nirgendwo anders +
Als im Geiste des Wachenden; +
Drum alles, was er dann sieht, ist +
Nur Bewußtsein des Wachenden.

{empty}67. Das Ding und seine Vorstellung +
Bedingen gegenseitig sich; +
Bestandlos ist für sich jedes, +
Nur im Bewußtsein stehn sie da.

{empty}68. Wie wir von einem bloß träumen, +
Daß er geboren wird, und stirbt, +
So sind all diese Weltwesen +
Wirklich und doch auch wirklich nicht.

{empty}69. Wie wir im Wahngebild schauen, +
Daß einer lebt und wieder stirbt, +
So sind all diese Weltwesen +
Wirklich und doch auch wirklich nicht.

{empty}70. Wie Zauberkunst uns läßt schauen, +
Daß einer lebt und wieder stirbt, +
So sind all diese Weltwesen +
Wirklich und doch auch wirklich nicht.

{empty}71. Keine Seele entsteht jemals, +
Kein Entstehn ist der ganzen Welt; +
Das ist die höchste Heilswahrheit, +
Daß es nirgend ein Werden gibt.

{empty}72. Was zweifach als Subjekt-Objekt +
Scheint, ist Bewußtseinsschwingung nur; +
Der Geist ist ewig objektlos, +
"An ihm haftet nichts", lehrt die Schrift.

{empty}73. Wie es künstlich durch Annahme, +
So ist es nicht in Wirklichkeit; +
Was andre Schulen annehmen, +
Ist für sie, nicht in Wirklichkeit.

{empty}74. Was als ewig sie annehmen +
Künstlich, ist wirklich ewig nicht; +
Das Resultat andrer Schulen +
Zeigt als Irrtum und werdend es.

{empty}75. An das, was nicht ist, Anpassung +
Beweist nicht, daß es Zweiheit gibt; +
Ist ihr Nichtsein erkannt, dann fällt +
Die Anpassung als zwecklos weg.

{empty}76. Wenn man nicht annimmt Ursachen +
In allen Reichen der Natur, +
So auch nicht ihre Vorstellung; +
Mit der Ursach' die Wirkung fällt.

{empty}77. Geist ist grundlos; das Nichtwerden, +
Zweiheitlos, ist ihm eigen stets; +
Geisterscheinung nur ist Zweiheit +
Des Ewigen, das alles ist.

{empty}78. Grundlosigkeit als wahr wissend, +
Verwerfend Einzel-Ursachen, +
Gelangt man zu dem furchtlosen, +
Wunschlosen, kummerlosen Ort.

{empty}79. Sich anpassend dem, was nicht ist, +
Bleibt in solches verstrickt der Geist; +
Der Dinge Nichts erkannt habend, +
Kehrt er zum Anhaftlosen sich.

{empty}80. Wer dies ergreift und nicht läßt mehr, +
Des Stand bleibt unbeweglich dann; +
Der.Weisen Ziel ist dies ew'ge +
Zweiheitlose Identischsein.

{empty}81. Das schlummerlose, traumlose +
Ew'ge ist dann sich selber Licht; +
"Für immer licht" ist dies Wesen, +
Ist diese Wesenheit an sich.

{empty}82. Gar leicht verbirgt er uns immer, +
Gar schwer enthüllt sein Wesen er, +
Solang wir einzeln auffassen +
Die Dinge, – er, der heilige.

{empty}83. "Er ist!" "Ist nicht!" "Ist und ist nicht!" +
"Er ist nicht nicht!" so denkend ihn +
Unstät, stät, zwiefach, neinsagend, +
Verbirgt sein Wesen sich der Tor.

{empty}84. Durch dieser vier Gesichtspunkte +
Verfolgung bleibt verborgen stets +
Der Heil'ge, unberührt durch sie, – +
Doch allschauend ist, wer ihn schaut.

{empty}85. Wer voll besitzt die Allschauung, +
Den zweiheitlosen Brahman-Ort, +
An dem nicht Anfang, Mitt', Ende, +
Dem bleibt nichts zu erstreben mehr.

{empty}86. Das heißt echte Gemütsruhe, +
Das ist die wahre Priesterzucht, +
Das ist der Selbstnatur Zähmung, +
Wer sie kennt, geht zur Ruhe ein.

{empty}87. Wahrnehmunghaft und objekthaft +
Ist die zweithafte Weltlichkeit (Wachen); +
Wahrnehmunghaft und objektlos +
Ist geläuterte Weltlichkeit (Traum).

{empty}88. Wahrnehmunglos und objektlos, +
Das heißt die Überweltlichkeit; +
Ihr Subjekt ist zugleich Objekt, +
So lehrten Weise aller Zeit.

{empty}89. Subjekt und die drei Objekte +
Stufenweis als in sich erkannt, – +
Daraus entsteht die Allschauung, +
Allerwärts des Hochsinnigen.

{empty}90. Erst frage man: was soll werden +
Geflohn, erkannt, erlangt und reif? +
Für's Erkennen gilt Wahrnehmung, +
Und so auch für die andern drei,

{empty}91. Alle Wesen sind ursprünglich +
Unbegrenzt und dem Baume gleich, +
Und nicht ist irgendwo Vielheit +
Unter ihnen, in keinem Sinn.

{empty}92. Alle Wesen sind ursprünglich +
Urerweckte (âdibuddha), das ist gewiß; – +
Wer dieses sich genug sein läßt, +
Der ist reif zur Unsterblichkeit.

{empty}93. Sie alle sind auch ursprünglich +
Urberuhigt, voll Seligkeit; +
Sich gleich alle und unteilbar, +
Ew'ge, reine Identität.

{empty}94. Doch diese Reinheit ist nicht mehr, +
Wenn sie vielfach zersplittern sich; +
Vielheitversunken, zwiespältig +
Heißen darum armselig sie.

{empty}95. Doch wem hier zur Gewißheit ward +
Die ewige Identität, +
Der weiß in dieser Welt Großes, +
Die Welt aber versteht es nicht.

{empty}96. Wissen des Ew'gen ist ewig +
Auch, mit nichts sonst befassend sich; +
Als nichtbefassend sich, heißt dies +
Wissen das unanhaftende (4,72. 79).

{empty}97. Doch wo die kleinste Ungleichheit +
Für wahr hält der unweise Geist, +
Da ist weder Nichtanhaftung +
Noch Weichen der Verdunkelung.

{empty}98. Alle Seelen sind ursprünglich +
Frei vom Dunkel und fleckenlos, +
Urerweckt schon und urerlöst +
Erwachen sie, der Meister spricht.

{empty}99. Wie die Sonne durch sich leuchtet, +
So Wissen ohne Dinge auch; +
Alle Dinge sind nur Wissen, – +
Unsagbar dem Erweckten selbst.

{empty}100. Die dunkle, überaus tiefe, +
Ew'ge, reine Identität, +
Der Einheit Stätte nach Kräften +
Erkannt habend, verehren wir!

xref:Quellen.adoc#Upanishad[Mandukya-Upanishad]
